import { useState } from "react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { FileBarChart, Sparkles, Loader2, CalendarRange, CalendarDays } from "lucide-react";
import ReactMarkdown from "react-markdown";
import api from "../lib/api";

export default function Reports() {
  const [period, setPeriod] = useState("weekly");
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(false);

  const generate = async (p) => {
    setPeriod(p); setLoading(true); setReport("");
    try { const { data } = await api.get(`/reports/${p}`); setReport(data.report); }
    catch { toast.error("Could not generate report"); }
    finally { setLoading(false); }
  };

  return (
    <div className="space-y-8" data-testid="reports-page">
      <div><p className="text-xs tracking-[0.2em] uppercase font-bold text-slate-400">Reflect & review</p><h1 className="font-display text-3xl sm:text-4xl font-semibold tracking-tight text-slate-900 mt-1">Reports</h1></div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <button data-testid="weekly-report-btn" onClick={() => generate("weekly")} disabled={loading}
          className={`group text-left rounded-3xl border p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg disabled:opacity-60 ${period === "weekly" && report ? "border-slate-900 bg-white" : "border-slate-200/60 bg-white"}`}>
          <div className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-orange-500"><CalendarDays strokeWidth={1.75} className="h-5 w-5" /></div>
          <h3 className="font-display mt-4 text-lg font-semibold text-slate-900">Weekly report</h3>
          <p className="mt-1 text-sm text-slate-500">AI summary of your week across every life area.</p>
        </button>
        <button data-testid="monthly-report-btn" onClick={() => generate("monthly")} disabled={loading}
          className={`group text-left rounded-3xl border p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg disabled:opacity-60 ${period === "monthly" && report ? "border-slate-900 bg-white" : "border-slate-200/60 bg-white"}`}>
          <div className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-500"><CalendarRange strokeWidth={1.75} className="h-5 w-5" /></div>
          <h3 className="font-display mt-4 text-lg font-semibold text-slate-900">Monthly report</h3>
          <p className="mt-1 text-sm text-slate-500">Deeper analytics, long-term trends and recommendations.</p>
        </button>
      </div>

      <div className="rounded-3xl border border-slate-200/60 bg-white p-6 sm:p-10 min-h-[300px]">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <Loader2 className="h-8 w-8 text-slate-400 animate-spin" />
            <p className="mt-4 text-sm text-slate-500">Your coach is analyzing your {period} data…</p>
          </div>
        ) : report ? (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
            <div className="flex items-center gap-2 mb-6 text-xs font-medium text-slate-400">
              <Sparkles className="h-4 w-4 text-blue-500" /> Generated by Dopame Coach · {period}
            </div>
            <div className="prose prose-slate max-w-none prose-headings:font-display prose-headings:font-semibold prose-h2:text-xl prose-h2:mt-6 prose-p:text-slate-600 prose-li:text-slate-600 prose-strong:text-slate-900">
              <ReactMarkdown>{report}</ReactMarkdown>
            </div>
          </motion.div>
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><FileBarChart strokeWidth={1.5} className="h-7 w-7" /></div>
            <h3 className="font-display mt-4 text-xl font-semibold text-slate-900">No report yet</h3>
            <p className="mt-1 text-sm text-slate-500">Pick a period above to generate your personalized growth report.</p>
          </div>
        )}
      </div>
    </div>
  );
}
